# Generated by Django 3.0.10 on 2020-10-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/images/prokects/')),
                ('link', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/services/'),
        ),
    ]
