# Generated by Django 3.0.10 on 2020-10-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20201012_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
