# Generated by Django 3.0.10 on 2020-10-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20201012_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/images/projects/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/images/services/'),
        ),
    ]
